INSERT INTO `privilege` (`privilege`,`description`,`uuid`) VALUES ('Add Allergies','Add allergies',uuid());
INSERT INTO `privilege` (`privilege`,`description`,`uuid`) VALUES ('Add HL7 Inbound Archive','Able to add an HL7 archive item',uuid());
INSERT INTO `privilege` (`privilege`,`description`,`uuid`) VALUES ('Add HL7 Inbound Exception','Able to add an HL7 error item',uuid());
INSERT INTO `privilege` (`privilege`,`description`,`uuid`) VALUES ('Add HL7 Inbound Queue','Able to add an HL7 Queue item',uuid());
INSERT INTO `privilege` (`privilege`,`description`,`uuid`) VALUES ('Add HL7 Source','Able to add an HL7 Source',uuid());
INSERT INTO `privilege` (`privilege`,`description`,`uuid`) VALUES ('Add Problems','Add problems',uuid());
INSERT INTO `privilege` (`privilege`,`description`,`uuid`) VALUES ('Add Visits','Able to add visits',uuid());
INSERT INTO `privilege` (`privilege`,`description`,`uuid`) VALUES ('Configure Visits','Able to choose encounter visit handler and enable/disable encounter visits',uuid());
INSERT INTO `privilege` (`privilege`,`description`,`uuid`) VALUES ('Delete HL7 Inbound Archive','Able to delete/retire an HL7 archive item',uuid());
INSERT INTO `privilege` (`privilege`,`description`,`uuid`) VALUES ('Delete HL7 Inbound Exception','Able to delete an HL7 archive item',uuid());
INSERT INTO `privilege` (`privilege`,`description`,`uuid`) VALUES ('Delete HL7 Inbound Queue','Able to delete an HL7 Queue item',uuid());
INSERT INTO `privilege` (`privilege`,`description`,`uuid`) VALUES ('Delete Visits','Able to delete visits',uuid());
INSERT INTO `privilege` (`privilege`,`description`,`uuid`) VALUES ('Edit Allergies','Able to edit allergies',uuid());
INSERT INTO `privilege` (`privilege`,`description`,`uuid`) VALUES ('Edit Problems','Able to edit problems',uuid());
INSERT INTO `privilege` (`privilege`,`description`,`uuid`) VALUES ('Edit Visits','Able to edit visits',uuid());
INSERT INTO `privilege` (`privilege`,`description`,`uuid`) VALUES ('Manage Address Hierarchy','Able to add/edit/delete address hierarchies',uuid());
INSERT INTO `privilege` (`privilege`,`description`,`uuid`) VALUES ('Manage Address Templates','Able to add/edit/delete address templates',uuid());
INSERT INTO `privilege` (`privilege`,`description`,`uuid`) VALUES ('Manage Concept Map Types','Able to add/edit/retire concept map types',uuid());
INSERT INTO `privilege` (`privilege`,`description`,`uuid`) VALUES ('Manage Concept Name tags','Able to add/edit/delete concept name tags',uuid());
INSERT INTO `privilege` (`privilege`,`description`,`uuid`) VALUES ('Manage Concept Reference Terms','Able to add/edit/retire reference terms',uuid());
INSERT INTO `privilege` (`privilege`,`description`,`uuid`) VALUES ('Manage Concept Stop Words','Able to view/add/remove the concept stop words',uuid());
INSERT INTO `privilege` (`privilege`,`description`,`uuid`) VALUES ('Manage Encounter Roles','Able to add/edit/retire encounter roles',uuid());
INSERT INTO `privilege` (`privilege`,`description`,`uuid`) VALUES ('Manage HL7 Messages','Able to add/edit/delete HL7 messages',uuid());
INSERT INTO `privilege` (`privilege`,`description`,`uuid`) VALUES ('Manage Implementation Id','Able to view/add/edit the implementation id for the system',uuid());
INSERT INTO `privilege` (`privilege`,`description`,`uuid`) VALUES ('Manage Location Attribute Types','Able to add/edit/retire location attribute types',uuid());
INSERT INTO `privilege` (`privilege`,`description`,`uuid`) VALUES ('Manage Location Tags','Able to add/edit/delete location tags',uuid());
INSERT INTO `privilege` (`privilege`,`description`,`uuid`) VALUES ('Manage Providers','Able to edit Provider',uuid());
INSERT INTO `privilege` (`privilege`,`description`,`uuid`) VALUES ('Manage Rule Definitions','Allows creation and editing of user-defined rules',uuid());
INSERT INTO `privilege` (`privilege`,`description`,`uuid`) VALUES ('Manage Tokens','Allows registering and removal of tokens',uuid());
INSERT INTO `privilege` (`privilege`,`description`,`uuid`) VALUES ('Manage Visit Attribute Types','Able to add/edit/retire visit attribute types',uuid());
INSERT INTO `privilege` (`privilege`,`description`,`uuid`) VALUES ('Manage Visit Types','Able to add/edit/delete visit types',uuid());
INSERT INTO `privilege` (`privilege`,`description`,`uuid`) VALUES ('Patient Dashboard - View Visits Section','Able to view the \'Visits\' tab on the patient dashboard',uuid());
INSERT INTO `privilege` (`privilege`,`description`,`uuid`) VALUES ('Remove Allergies','Remove allergies',uuid());
INSERT INTO `privilege` (`privilege`,`description`,`uuid`) VALUES ('Remove Problems','Remove problems',uuid());
INSERT INTO `privilege` (`privilege`,`description`,`uuid`) VALUES ('Update HL7 Inbound Archive','Able to update an HL7 archive item',uuid());
INSERT INTO `privilege` (`privilege`,`description`,`uuid`) VALUES ('Update HL7 Inbound Exception','Able to update an HL7 archive item',uuid());
INSERT INTO `privilege` (`privilege`,`description`,`uuid`) VALUES ('Update HL7 Inbound Queue','Able to update an HL7 Queue item',uuid());
INSERT INTO `privilege` (`privilege`,`description`,`uuid`) VALUES ('Update HL7 Source','Able to update an HL7 Source',uuid());
INSERT INTO `privilege` (`privilege`,`description`,`uuid`) VALUES ('View Concept Map Types','Able to view concept map types',uuid());
INSERT INTO `privilege` (`privilege`,`description`,`uuid`) VALUES ('View Concept Reference Terms','Able to view concept reference terms',uuid());
INSERT INTO `privilege` (`privilege`,`description`,`uuid`) VALUES ('View Database Changes','Able to view database changes from the admin screen',uuid());
INSERT INTO `privilege` (`privilege`,`description`,`uuid`) VALUES ('View Encounter Roles','Able to view encounter roles',uuid());
INSERT INTO `privilege` (`privilege`,`description`,`uuid`) VALUES ('View HL7 Inbound Archive','Able to view an HL7 archive item',uuid());
INSERT INTO `privilege` (`privilege`,`description`,`uuid`) VALUES ('View HL7 Inbound Exception','Able to view an HL7 archive item',uuid());
INSERT INTO `privilege` (`privilege`,`description`,`uuid`) VALUES ('View HL7 Inbound Queue','Able to view an HL7 Queue item',uuid());
INSERT INTO `privilege` (`privilege`,`description`,`uuid`) VALUES ('View HL7 Source','Able to view an HL7 Source',uuid());
INSERT INTO `privilege` (`privilege`,`description`,`uuid`) VALUES ('View Location Attribute Types','Able to view location attribute types',uuid());
INSERT INTO `privilege` (`privilege`,`description`,`uuid`) VALUES ('View Providers','Able to view Provider',uuid());
INSERT INTO `privilege` (`privilege`,`description`,`uuid`) VALUES ('View Rule Definitions','Allows viewing of user-defined rules. (This privilege is not necessary to run rules under normal usage.)',uuid());
INSERT INTO `privilege` (`privilege`,`description`,`uuid`) VALUES ('View Visit Attribute Types','Able to view visit attribute types',uuid());
INSERT INTO `privilege` (`privilege`,`description`,`uuid`) VALUES ('View Visit Types','Able to view visit types',uuid());
INSERT INTO `privilege` (`privilege`,`description`,`uuid`) VALUES ('View Visits','Able to view visits',uuid());
